package uk.ac.soton.comp1206.event;


import uk.ac.soton.comp1206.game.GamePiece;

/**
 * Listen to the next game piece which is generated by the Game
 */
public interface NextPieceListener {

      /**
       * Update the current and following game pieces
       * @param currentPiece current game piece
       * @param nextPiece following game piece
       */
      void nextPiece(GamePiece currentPiece, GamePiece nextPiece);
}
